// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig():Promise<string>;

export function SaveConfig(arg1:string):Promise<void>;

export function SelectConfigFile():Promise<string>;

export function TestSource(arg1:string):Promise<string>;
